### ISSUE TITLE
Aria attributes would be another nice addition

### ISSUE THREAD

**Issue by subhaze** [geoffmcl/tidy-fork#10]
Extensive list of valid `aria-*` state/values

http://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def

**Comment by geoffmcl** [comment]
Hi Michael,

Thank you for your post, and sorry for the
delay in my response...

I have just completed a merge with -
https://github.com/balthisar/tidy-html5/tree/geoffmcl-restart
which includes ARIA support...

It is presently in a branch -
$ git checkout geoffmcl-restart

Have only just started testing all the aria
attributes... but is looking good... a WIP...

If you get a chance to test it would appreciate
any feedback...

Regards,
Geoff.

**Comment by subhaze** [comment]
@geoffmcl thanks! I'll aim to make time this week to test this out, much appreciated!

**Comment by subhaze** [comment]
@geoffmcl I just ran some tests and it looks like all the attributes are no longer throwing, yay!

One question though, would it be out of scope for this tool to check for valid attribute values?

Examples:

aria autocomplete should only have the following values
`aria-autocomplete="inline|list|both|none"`
and should be used on an element with `role="combobox|textbox"`

**Comment by geoffmcl** [comment]
Hi Michael,

Yes, glad some level of ARIA has been
added...

But, no at this moment, each attribute is
NOT checked for valid values, like say -
  aria-autocomplete="inline|list|both|none"
etc, but hopefully one day...

Like say CheckScroll() has values "no", "auto",
"yes"... etc, etc... But this requires building
up such tables, handling code...

Hopefully all in good time ;=))

Regards,
Geoff.

**Comment by subhaze** [comment]
OK, I was thinking that might be the case :)

I'll close this issue since all seems well on no longer throwing on that set of attributes, but do you think it would be worth efforts on starting up a set of tickets for each attribute that required specific values?

**Comment by geoffmcl** [comment]
Thanks...
