### ISSUE TITLE
cred

### ISSUE THREAD

**Issue by pedromorgan** [geoffmcl/tidy-fork#12]
Work here and compiles

Ta Mc Lean

**Comment by geoffmcl** [comment]
@pedromorgan Hi Pete, you do know that ALL development has now moved to the htacg repo, presently in the develop-500 branch, but hope to get that in master SOON!

$ git clone git@github.com:htacg/tidy-html5.git
$ git checkout develop-500

Have been sometimes updating here, also in the develop-500 branch, but will probably eventually delete this 'fork' when we have relased a tidy 5.0.0 again SOON I hope ;=))
