### ISSUE TITLE
ARIA Checking

### ISSUE THREAD

**Issue by anEffingChamp** [geoffmcl/tidy-fork#5]
Can the validator check for common class names indicating that an ARIA role should be in use? It would be a great reminder to make our pages more accessible.

* http://oaa-accessibility.org/testsuites/
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets

Specifically I read through this post, and thought that its suggestions for output were worth a look. It is focused on ARIA checking, but we can probably stand to be more detailed in output in general.

* http://www.paciellogroup.com/blog/2009/01/how-can-i-validate-xhtml-aria/

**Comment by geoffmcl** [comment]
Hi Jonathan,

Thank you for your post, and sorry for the
delay in my response...

I have just completed a merge with -
https://github.com/balthisar/tidy-html5/tree/geoffmcl-restart
which includes ARIA support...

It is presently in a branch -
$ git checkout geoffmcl-restart

Have only just started testing all the aria
attributes... but is looking good... a WIP...

If you get a chance to test it would appreciate
any feedback...

Regards,
Geoff.

**Comment by geoffmcl** [comment]
@anEffingChamp for the present I have moved my efforts to what I hope will be the final 'single' HTML Tidy -
https://github.com/htacg/tidy-html5 as part of the HTACG group -
http://www.w3.org/community/htacg/
http://www.html-tidy.org/
https://lists.w3.org/Archives/Public/public-htacg/
etc...

So to get the latest code -
$ git clone git@github.com:htacg/tidy-html5.git
$ cd tidy-html5
$ git checkout develop-500

If this all works out, I may close this 'fork', but for the present have kept it in step, in the develop-500 branch...

I think you will find the htacg develop-500 now has quite full aria-* support, so will close this, but if you find something missing or wrong please open an issue there... thanks...
