### ISSUE TITLE
"allowfullscreen" is wrongly recognized as proprietary in <iframe>

### ISSUE THREAD

**Issue by eksperimental** [geoffmcl/tidy-fork#6]
``
line 74 column 1 - Warning: <iframe> proprietary attribute "allowfullscreen"
line 74 column 1 - Warning: <iframe> proprietary attribute "mozallowfullscreen"
line 74 column 1 - Warning: <iframe> proprietary attribute "webkitallowfullscreen"
``
source:
``<iframe src="http://player.vimeo.com/video/46709928" class="video" width="600" height="337" allowfullscreen mozallowfullscreen webkitallowfullscreen></iframe>``

"allowfullscreen" is valid, according to [mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allowfullscreen)
actually, the proprietary ones mozallowfullscreen and webkitallowfullscreen have been deprecated, in favor of allowfullscreen
but I couldn't find the info inthe [html5 refence](http://www.w3.org/TR/html5/embedded-content-0.html#process-the-iframe-attributes)

**Comment by geoffmcl** [comment]
Hi eksperimental,

Only found a reference in a 'draft' document -
http://www.w3.org/html/wg/drafts/html/master/single-page.html#attr-iframe-allowfullscreen

But the W3C validator only flags mozallowfullscreen and
webkitallowfullscreen, so have 'fixed' tidy-fork, in the
geoffmcl-restart branch -

$ git checkout geoffmcl-restart

It would be appreciated if you could get a chance to
check, and if ok, close #6

Regards,
Geoff.

**Comment by subhaze** [comment]
Checked this on my end and all seems well now :+1: 

line 7 column 17 - Warning: <iframe> proprietary attribute "mozallowfullscreen"
line 7 column 17 - Warning: <iframe> proprietary attribute "webkitallowfullscreen"
Info: Document content looks like HTML5
2 warnings, 0 errors were found!

```html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<iframe src="http://example.com" allowfullscreen mozallowfullscreen webkitallowfullscreen ></iframe>
	</body>
</html>
```

One thing I did notice though is you can add `allowfullscreen="false"` and things still show up fine. The spec states the following

"If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name"
http://www.w3.org/html/wg/drafts/html/master/single-page.html#boolean-attribute

I'm not sure how difficult this would be to pull of though...

**Comment by geoffmcl** [comment]
Hi Michael,

Glad have now got 'allowfullscreen' through, but
I would admit it was just a nasty quick fix ;=()

As you point out, really allowfullscreen="false"
should probably be a warning, or even an error
from reading the Note:, my emphasis...

"The values "true" and "false" are NOT allowed on
  boolean attributes. To represent a false value, the
  attribute has to be omitted altogether."

Seems only allowfullscreen, or
allowfullscreen=allowfullscreen, UGH!, or
allowfullscreen="", another UGH!, should be
allowed...

And should perhaps be dropped, or fixed, if you
asked for cleaning...

But that should be a separate Bug or Feature
request... Have not yet decided which ;=))

Thanks for testing and reporting...

Regards,
Geoff.

**Comment by geoffmcl** [comment]
@subhaze thank for opening the clearer #11 for this, and will close here.

For the present I have moved my efforts to what I hope will be the 'single' HTML Tidy -
https://github.com/htacg/tidy-html5 as part of the HTACG group -
http://www.w3.org/community/htacg/

So to get the latest code -
$ git clone git@github.com:htacg/tidy-html5.git
$ cd tidy-html5
$ git checkout develop-500

If this all works out, I may close this 'fork', but for the present have kept it in step, in the develop-500 branch...

Will keep this attribute checking in mind as things move forward...

**Comment by eksperimental** [comment]
thank you guys
