### ISSUE TITLE
Treat elements ids as case-sensitive

### ISSUE THREAD

**Issue by eksperimental** [geoffmcl/tidy-fork#7]
````
<span id="test"></span>
<span id="Test"></span>
<span id="TEST"></span>
````
gives a warning:
````
line 74 column 1 - Warning: <span> anchor "Test" already defined
line 75 column 1 - Warning: <span> anchor "TEST" already defined
````

that's ok for html4, but it is not the case in html5, as they are considered different elements
http://www.w3.org/TR/html5/disabled-elements.html#case-sensitivity

**Comment by geoffmcl** [comment]
Hi eksperimental,

Thank you for the report, and sorry about the
delay in my response...

Hmmm, this is QUITE difficult ;=((

As you point out, for html4 (and less), ids 'test',
'Test' and 'TEST' are the same, thus the warning.

So how to keep this behaviour if the documents is
html4, while at the same time treat them differently
for html5???

This check is done AFTER the parsing of the whole
document, so could possibly 'guess' if it looks
like htm5 and act differently...

Or it could be based on say the --doctype html5
user config input. If this doctype is given, only
then treat it as html5...

Need to think and consult on this... Will be back
soonest...

Regards,
Geoff.

**Comment by subhaze** [comment]
Just jumping in with a thought. Would it be a bad thing if tidy-html5 only focused on html5 and allowed the existing tidy be the go to for html4?

**Comment by eksperimental** [comment]
@subhaze oh really, I thought tidy-html5 was a fork of tidy(-html4) that focused only on html5.
@geoffmcl if the document doesn't explicitly say it's html4, i think tidy-HTML5 should treat it as html5.

what you guys think?

**Comment by subhaze** [comment]
@eksperimental you are right, it's a fork to add additional support. I was just throwing out a thought on if things begin to be very difficult on keeping BC, potentially moving to just HTML5.

**Comment by geoffmcl** [comment]
Hi,

While I agree life would be MUCH easier if
we just separated the two - leave tidy to do
html4 and earlier, and have tidy5 treat everything
as html5, that has /NEVER/ been the aim!

And such a library separation also represents
additional maintenance, like when a bug is
reported that applies to both... two sources,
or a very messy macro switched source... UGH!

At present tidy5 tries to guess what type of
document it is... if it finds tags, attributes,
features, etc only in html5, then it chooses
html5... And likewise for html4, or earlier...

Also there is a --doctype html5 command that
indicates to tidy5 that you want the output with
a html5 doctype...

The options for doctype are html5, omit, auto,
strict, transitional, and user, with auto
being the default.

So far this has been quite successful... and
for the present will continue to try to have
full functionality in the next release of
tidy[5] ;=))

And you will note the W3C validator is now trying
to do the same... so this is a push for the
single, very intelligent, tidy[5]...

Regards,
Geoff.

**Comment by subhaze** [comment]
Geoff, thanks for the details. I'm glad to see you're up for the task on
keeping everything supported :)

And again, many thanks for putting life back into this tool.

**Comment by geoffmcl** [comment]
Development moved to <a href="https://github.com/htacg/tidy-html5">htacg/tidy-html5</a>, where this issue has been fixed.
