### ISSUE TITLE
add aria role attribute support

### ISSUE THREAD

**Issue by subhaze** [geoffmcl/tidy-fork#8]
Error received using the `role` attribute: `Warning: <li> proprietary attribute "role"`

http://www.w3.org/WAI/PF/aria/usage#usage_intro
`<li role="menuitem">Open file…</li>`

**Comment by geoffmcl** [comment]
Hi Michael,

As mentioned this should now be fixed in the
geoffmcl-restart branch -
$ git checkout geoffmcl-restart

If you get a chance to check and advise,
would be appreciated...

Regards,
Geoff.

**Comment by subhaze** [comment]
I'm going to make a more complete HTML file to test out the other aria attributes you've added, but on my current project I can confirm `role` is now fixed.

**Comment by geoffmcl** [comment]
Hi Michael (alias=subhaze),

Thank you for reporting and closing #8...

Look forward to any further problems you
find, encounter...

All for a better Tidy5 release... soon I
hope...

Regards,
Geoff.

**Comment by subhaze** [comment]
No problem at all @geoffmcl and I'm very glad to see you working on updating this! I'll try to help where I can, C isn't a lang I know but I can definitely help test it :)
